version: '3.8'

services:
  postgres-db:
    image: postgres:17-alpine
    container_name: spring_de_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: proyect_prueba
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: